In [2]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("cars.csv")
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [7]:
df["horsepower"].value_counts()

68     19
70     11
69     10
116     9
110     8
95      7
88      6
62      6
101     6
160     6
114     6
84      5
97      5
102     5
145     5
82      5
76      5
111     4
92      4
123     4
86      4
90      3
73      3
85      3
207     3
182     3
121     3
152     3
112     2
56      2
161     2
156     2
94      2
52      2
?       2
162     2
155     2
184     2
100     2
176     2
55      1
262     1
134     1
115     1
140     1
48      1
58      1
60      1
78      1
135     1
200     1
64      1
120     1
72      1
154     1
288     1
143     1
142     1
175     1
106     1
Name: horsepower, dtype: int64

In [9]:
df["normalized-losses"].replace("?", np.nan, inplace=True)
df["horsepower"].replace("?", np.nan, inplace=True)

In [10]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3               NaN  alfa-romero       gas  convertible   
1          3               NaN  alfa-romero       gas  convertible   
2          1               NaN  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [12]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values = np.nan, strategy="mean")
df[["normalized-losses", "horsepower"]] = si.fit_transform(df[["normalized-losses", "horsepower"]])

In [13]:
df.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [15]:
catcol = df.select_dtypes(object).columns

In [16]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df[catcol] = oe.fit_transform(df[catcol])

In [17]:
df.head()

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0          3              122.0   0.0        1.0         0.0           2.0   
1          3              122.0   0.0        1.0         0.0           2.0   
2          1              122.0   0.0        1.0         2.0           2.0   
3          2              164.0   1.0        1.0         3.0           1.0   
4          2              164.0   1.0        1.0         3.0           0.0   

   engine-location  width  height  engine-type  engine-size  horsepower  \
0              0.0   64.1    48.8          0.0          130       111.0   
1              0.0   64.1    48.8          0.0          130       111.0   
2              0.0   65.5    52.4          5.0          152       154.0   
3              0.0   66.2    54.3          3.0          109       102.0   
4              0.0   66.4    54.3          3.0          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

In [19]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [20]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.3, random_state=1)

In [21]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(xtrain, ytrain)
ypred = linreg.predict(xtest)

In [22]:
from sklearn.metrics import r2_score
print(r2_score(ytest, ypred))

0.796556678039738


In [24]:
train = linreg.score(xtrain, ytrain)
test = linreg.score(xtest, ytest)

print(f"Training Accuracy : {train}\nTesting Accuracy : {test}")

Training Accuracy : 0.8504573774895472
Testing Accuracy : 0.796556678039738


In [25]:
#Training = high accuracy = low Bias
#Testing = low accuracy = high variance
# low Bias + high variance = Overfitting

In [28]:
linreg.coef_

array([ 4.51384957e+01,  1.53127607e+00, -2.00099087e+02, -6.22650015e+02,
       -1.70235175e+02,  1.86860719e+03,  1.64133620e+04,  7.89452171e+02,
        3.62663990e+02,  2.83174279e+02,  9.83682875e+01, -1.08169245e+01,
        3.08017854e+02, -4.17024371e+02])

Regularization using Ridge

In [29]:
from sklearn.linear_model import Ridge, Lasso
l2 = Ridge(alpha = 10)   #alpha is selected randomly
l2.fit(xtrain, ytrain)
ypred = l2.predict(xtest)

In [30]:
train = l2.score(xtrain, ytrain)
test = l2.score(xtest, ytest)

print(f"Training Accuracy : {train}\nTesting Accuracy : {test}")

Training Accuracy : 0.8109538582620313
Testing Accuracy : 0.8150222867376528


In [31]:
l2.coef_

array([ 2.08658930e+02, -5.60173023e-01, -1.86340249e+02, -9.06610516e+02,
       -6.30655861e+02,  1.56860422e+03,  2.57047785e+03,  3.64420144e+02,
        5.72916414e+02,  5.15948757e+02,  1.04441215e+02,  2.21332730e+01,
        2.11271281e+02, -2.72864381e+02])

Regularization using Lasso

In [32]:
l1 = Lasso(alpha = 10)   #alpha is selected randomly
l1.fit(xtrain, ytrain)
ypred = l1.predict(xtest)

In [33]:
train = l1.score(xtrain, ytrain)
test = l1.score(xtest, ytest)

print(f"Training Accuracy : {train}\nTesting Accuracy : {test}")

Training Accuracy : 0.850322100477304
Testing Accuracy : 0.7982450097819802


In [34]:
l1.coef_

array([ 4.30275855e+01,  1.54304858e+00, -1.98340491e+02, -5.37967579e+02,
       -1.81289126e+02,  1.83640473e+03,  1.57130274e+04,  7.69644647e+02,
        3.68604731e+02,  2.83851156e+02,  9.92737590e+01, -9.63869876e+00,
        2.96678686e+02, -4.03230505e+02])

Finding best alpha value by hyperparameter tuning

In [39]:
for i in range(150,200):
  l1 = Lasso(alpha = i)
  l1.fit(xtrain, ytrain)

  train = l1.score(xtrain, ytrain)
  test = l1.score(xtest, ytest)

  print(f"{i} : {train}     {test}")

150 : 0.8212288879856349     0.8124969899539802
151 : 0.8208421468238061     0.8125456274822552
152 : 0.8204526518423789     0.8125934728624998
153 : 0.8200607762157636     0.8126404383406126
154 : 0.8196661304388356     0.8126866131583909
155 : 0.8192691148773523     0.812731907864298
156 : 0.8188695301369727     0.8127763675886549
157 : 0.818467171522371     0.8128200339758355
158 : 0.818062449862035     0.8128628223230776
159 : 0.8176549464501084     0.8129048166168775
160 : 0.8172450881050913     0.8129459336049878
161 : 0.8168324400154192     0.8129862557319264
162 : 0.8164174452457786     0.8130257013815376
163 : 0.8159998820785825     0.813064312010476
164 : 0.8155795285150105     0.813102124478007
165 : 0.8151568303042498     0.8131390636923392
166 : 0.8147313271293926     0.8131752048184052
167 : 0.8143034914835354     0.8132104730535141
168 : 0.8138728445987573     0.8132449418027806
169 : 0.8134398734696936     0.8132785388258221
170 : 0.8130040832573875     0.81331133513107

In [41]:
l1 = Lasso(alpha = 168)   #alpha is selected from above by tallying the trining and testing accuracy
l1.fit(xtrain, ytrain)
ypred = l1.predict(xtest)

In [42]:
train = l1.score(xtrain, ytrain)
test = l1.score(xtest, ytest)

print(f"Training Accuracy : {train}\nTesting Accuracy : {test}")

Training Accuracy : 0.8138728445987573
Testing Accuracy : 0.8132449418027806


Trying to increase Ridge accuracy by hyperparameter tuning

In [46]:
for i in range(1,10):
  l2 = Ridge(alpha = i)
  l2.fit(xtrain, ytrain)

  train = l2.score(xtrain, ytrain)
  test = l2.score(xtest, ytest)

  print(f"{i} : {train}     {test}")

1 : 0.8436019887231635     0.8074518758147273
2 : 0.8356568294333325     0.8110292248150512
3 : 0.8295966853783839     0.8126933383890033
4 : 0.8250050456621351     0.8136148645029297
5 : 0.8214255248858178     0.8141745853539419
6 : 0.8185497905642732     0.8145301242133356
7 : 0.8161775446879698     0.8147582608502815
8 : 0.8141763553347592     0.8149010602831955
9 : 0.8124561449821565     0.8149836949253053


from above we conclude that alpha = 8 for best fit model

In [51]:
from sklearn.linear_model import Ridge, Lasso
l2 = Ridge(alpha = 8)   #alpha is selected randfrom above hyperparameter tuningomly
l2.fit(xtrain, ytrain)
ypred = l2.predict(xtest)

In [50]:
train = l2.score(xtrain, ytrain)
test = l2.score(xtest, ytest)

print(f"Training Accuracy : {train}\nTesting Accuracy : {test}")

Training Accuracy : 0.8141763553347592
Testing Accuracy : 0.8149010602831955
